### ISSUE TITLE
Not compatible with the hpp-fcl version 0.5.1

### ISSUE THREAD

**Issue by pFernbach** [humanoid-path-planner/hpp-affordance#4]
hpp-fcl now use Eigen types, even with the compilation option set to FCL_HAVE_EIGEN  = OFF.
The code of this package is not compatible with the Eigen types. Mostly because of missing function
`sqrLength` and `normalize`

**Comment by pFernbach** [comment]
Solved, but we should remove the now-useless compilation option in hpp-fcl.

**Comment by jmirabel** [comment]
You are right. I did it after I saw your problem: https://github.com/humanoid-path-planner/hpp-fcl/pull/27
